# Generated by Django 3.1.2 on 2021-02-24 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('key', models.CharField(max_length=8)),
                ('content', models.BinaryField()),
                ('salt', models.BinaryField(blank=True, null=True)),
                ('has_custom_passphrase', models.BooleanField(default=False)),
                ('lifetime', models.IntegerField(choices=[(604800, '7 days'), (259200, '3 days'), (86400, '1 day'), (43200, '12 hours'), (14400, '4 hours'), (3600, '1 hour'), (1800, '30 minutes'), (300, '5 minutes')])),
            ],
        ),
    ]
